name: AutoBuild .NET

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Build PC version
        run: dotnet build TheOtherRoles/TheOtherRoles.csproj --configuration PC

      - name: Build Android version
        run: dotnet build TheOtherRoles/TheOtherRoles.csproj --configuration Android

      - name: Upload PC version
        uses: actions/upload-artifact@v4
        with:
          name: TheOtherRoles-Win.dll
          path: TheOtherRoles/bin/PC/net6.0/TheOtherRoles.dll

      - name: Upload Android version
        uses: actions/upload-artifact@v4
        with:
          name: TheOtherRoles-Android.dll
          path: TheOtherRoles/bin/Android/net6.0/TheOtherRoles.dll
